#Get Libraries
#packages <- c("jsonlite", "tidyverse", "dplyr", "readr", "data.table", "stringr", "rvest", "stringi", "XML", "selectr", "gdata", "rvest", "scales", "gdata", "formattable", "flexdashboard", "jsonlite")
#install.packages(packages)
#Load Libraries
#lapply(packages, library, character.only = TRUE)

library(tidyjson)
library(dplyr)
library(tidyr)
library(readr)
library(data.table)
library(stringr)
library(rvest)
library(stringi)
library(XML)
library(plyr)
library(selectr)
library(rsconnect)
library(flexdashboard)
library(gdata)
library(jsonlite)
library(scales)
